services:
  database:
    image: postgres
    container_name: database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d expense_db"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=expense_db
    ports:
      - 5432:5432

  backend:
    build: api
    ports:
      - 6400:6400
    healthcheck:
      test: curl --fail http://localhost:6400/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - DB_URL=postgresql+asyncpg://admin:password@database:5432/expense_db
    depends_on:
      database:
        condition: service_healthy
        restart: true

  frontend:
    build: ui
    ports:
      - 3000:3000
    environment:
      - BACKEND_BASE_URL=backend:6400
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      database:
        condition: service_healthy
        restart: true
      backend:
        condition: service_healthy
        restart: true

volumes:
  db-data:
