name: Bug Fix
description: File a bug fix for the app
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
    validations:
      required: true

  - type: checkboxes
    id: components_affected
    attributes:
      label: Components Affected
      description: Select all components related to this issue
      options:
        - label: Frontend
          value: frontend
        - label: Backend
          value: backend
        - label: Infrastructure
          value: infra
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can the bug be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: screenshots_logs
    attributes:
      label: Screenshots or Logs (if applicable)
      description: Attach screenshots, error messages, or logs that might help diagnose the issue.
      placeholder: Paste logs or attach images here.
