name: Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        type: string
        required: true
      aws_secret_access_key:
        type: string
        required: true
      aws_session_token:
        type: string
        required: true
      aws_region:
        type: string
        required: true
        default: "us-east-1"
      branch:
        description: "Branch to run workflow on"
        required: true
        default: "main"

env:
  TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
  TF_VAR_auth0_domain: ${{ secrets.TF_VAR_AUTH0_DOMAIN }}
  TF_VAR_auth0_client_id: ${{ secrets.TF_VAR_AUTH0_CLIENT_ID }}
  TF_VAR_auth0_client_secret: ${{ secrets.TF_VAR_AUTH0_CLIENT_SECRET }}
  TF_VAR_sentry_dsn: ${{ secrets.TF_VAR_SENTRY_DSN }}

jobs:
  terraform_checks:
    name: Runs a terraform chceks
    runs-on: ubuntu-latest
    if: github.event.inputs.branch == 'main'
    permissions:
      contents: read
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: infra

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: infra

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

  terraform_deploy:
    name: Runs a terraform deployment
    runs-on: ubuntu-latest
    needs: terraform_checks
    if: github.event.inputs.branch == 'main'
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: infra
    outputs:
      planfile: tfplan.binary
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan.binary
          terraform show -no-color tfplan.binary > tfplan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan.binary

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false tfplan.binary
        working-directory: infra
