name: Infrastructure Plan

on:
  workflow_dispatch:
    inputs:
      aws:
        type: string
        description: AWS credentials because I can't create a runner user so it has to be manual
        required: true
      branch:
        description: "Branch to run workflow on"
        required: true
        default: "main"

jobs:
  terraform_deploy:
    name: Runs a terraform deployment
    runs-on: ubuntu-latest
    if: github.event.inputs.branch == 'main'
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: infra
    outputs:
      planfile: tfplan.binary
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export credentials
        run: |
          mkdir ~/.aws
          echo ${{ github.event.inputs.aws }} | tr " " "\n" > ~/.aws/credentials

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: infra

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: infra

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan.binary
          terraform show -no-color tfplan.binary > tfplan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan.binary

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers:
          minimum-approvals: 1
          issue-title: "Deploying infra"
          issue-body: "Please approve or deny the deployment of infra"
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: "approve,yes,y"
          additional-denied-words: "no,deny,n"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false tfplan.binary
        working-directory: infra
