name: Run tests and collect coverage
on:
  push:
  pull_request:
jobs:
  backend_tests:
    name: Runs backend tests and generates a coverage report for them.
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Get test DB started with docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          services: database

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=expenseflow --cov-report=term-missing --cov-report=xml:coverage.xml --cov-report=html:htmlcov

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: ./coverage.xml

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: ./htmlcov
